### ISSUE TITLE
SearchComponent 설계 및 구현

### ISSUE THREAD

**Issue by SeungrokYoon** [SeungrokYoon/search-clinical-trial#1]
# Todo
## This Issue will address
- [x] `useDebounce` custom hook for deferring API call in input field
- [x] Display search results in `SearchResultList` component

## Further Todo
- [ ] `Cache` API call results  
- [ ] Use local / Redux-toolkit/ Recoil for caching query results by 'query alias'

**Comment by SeungrokYoon** [comment]
useDebounce는 함수를 받아서 디바운스된 함수를 리턴하는 커스텀 훅으로 작성할 예정
