### ISSUE TITLE
Cache API data

### ISSUE THREAD

**Issue by SeungrokYoon** [SeungrokYoon/search-clinical-trial#4]
# Todo

## This issue will address
- [ ] `Cache` API call results  
- [ ] Use  Redux-toolkit for caching query results by 'query alias'
- [ ] Refactor to class CacheObject
